In [2]:
#### sql work ###########  we want to load the two tables in SQL and return a query that return a join of the 
########  2 tables joined on the tail number of the planese

In [1]:
from __future__ import print_function, division

# Get pandas and postgres to work together
import psycopg2 as pg
import pandas as pd
import pandas.io.sql as pd_sql
pd.set_option('display.max_columns', 200) 
# We are also going to do some basic viz
import matplotlib.pyplot as plt

%matplotlib inline

In [9]:
# Postgres info to connect

connection_args = {
    'host': '18.237.80.189', # You'll have to update this to your IP
    'user': 'ubuntu',    # username
    'dbname': 'flights',   # DB that we are connecting to
    'port': 5432         # port we opened on AWS
}

# We will talk about this magic Python trick!
connection = pg.connect(**connection_args)

In [44]:
query = """
        CREATE TABLE avion (
          TailNum TEXT,
          manufacturer TEXT,
          mfr_year TEXT,
          model TEXT,
          serial_number TEXT
            );
            """

#pd_sql.read_sql(query, connection)
# make a cursor
#cursor = connection.cursor()

# make a query (sets the cursor pointing at the first record)
#cursor.execute(query)

In [45]:
cursor.execute("rollback;")

In [ ]:
# there is a step to copy the tail1.csv and and the delays1.csv to aws ubuntu
# cd in the mcnulty project directory
# scp -i ~/.ssh/tintin-project.pem delays1.csv ubuntu@18.237.80.189:~/.
# scp -i ~/.ssh/tintin-project.pem tail1.csv ubuntu@18.237.80.189:~/.

In [12]:
query = """

COPY avion FROM '/home/ubuntu/tail1.csv' DELIMITER ',' CSV HEADER;

            """

#pd_sql.read_sql(query, connection)
# make a cursor
cursor = connection.cursor()

# make a query (sets the cursor pointing at the first record)
cursor.execute(query)

In [3]:
query = "SELECT * FROM avion limit 5;"

pd_sql.read_sql(query, connection)

  tailnum      manufacturer mfr_year        model serial_number
0  N933EV    BOMBARDIER INC     2005  CL-600-2B19          8022
1  N917WN            BOEING     2008      737-7H4         36624
2  N438WN            BOEING     2003      737-7H4         29833
3  N283VA            AIRBUS     2015     A320-214          6787
4  N473UA  AIRBUS INDUSTRIE     2001     A320-232          1469

In [16]:
query = """
        CREATE TABLE retard (
            Year TEXT,
             Quarter TEXT,
             Month TEXT,
             DayofMonth TEXT,
             DayOfWeek TEXT,
             UniqueCarrier TEXT,
             AirlineID TEXT,
             TailNum TEXT,
             FlightNum TEXT,
             OriginAirportID TEXT,
             OriginCityMarketID TEXT,
             Origin TEXT,
             OriginStateFips TEXT,
             OriginStateName TEXT,
             DestAirportID TEXT,
             DestCityMarketID TEXT,
             Dest TEXT,
             DestStateFips TEXT,
             DestStateName TEXT,
             CRSDepTime TEXT,
             DepTime TEXT,
             DepDelay TEXT,
             DepDelayMinutes TEXT,
             DepDel15 TEXT,
             DepartureDelayGroups TEXT,
             CRSArrTime TEXT,
             ArrTime TEXT,
             ArrDelay TEXT,
             ArrDelayMinutes TEXT,
             ArrDel15 TEXT,
             ArrivalDelayGroups TEXT,
             Cancelled TEXT,
             AirTime TEXT,
             Flights TEXT,
             Distance TEXT,
             DistanceGroup TEXT,
             CarrierDelay TEXT,
             WeatherDelay TEXT,
             NASDelay TEXT,
             SecurityDelay TEXT,
             LateAircraftDelay TEXT
                );
            """

#  'Dest',
#pd_sql.read_sql(query, connection)
# make a cursor
cursor = connection.cursor()

# make a query (sets the cursor pointing at the first record)
cursor.execute(query)

In [17]:
query = """

COPY retard FROM '/home/ubuntu/delays1.csv' DELIMITER ',' CSV HEADER;

            """

#pd_sql.read_sql(query, connection)
# make a cursor
cursor = connection.cursor()

# make a query (sets the cursor pointing at the first record)
cursor.execute(query)

In [4]:
query = "SELECT * FROM retard limit 5;"

pd_sql.read_sql(query, connection)

,year,quarter,month,dayofmonth,dayofweek,uniquecarrier,airlineid,tailnum,flightnum,originairportid,origincitymarketid,origin,originstatefips,originstatename,destairportid,destcitymarketid,dest,deststatefips,deststatename,crsdeptime,deptime,depdelay,depdelayminutes,depdel15,departuredelaygroups,crsarrtime,arrtime,arrdelay,arrdelayminutes,arrdel15,arrivaldelaygroups,cancelled,airtime,flights,distance,distancegroup,carrierdelay,weatherdelay,nasdelay,securitydelay,lateaircraftdelay
0,2015,3,8,3,1,WN,19393,N935WN,253,13244,33244,MEM,47,Tennessee,13204,31454,MCO,12,Florida,1350,1353.0,3.0,3.0,0.0,0.0,1650,1700.0,10.0,10.0,0.0,0.0,0.0,109.0,1.0,684.0,3,None,None,None,None,None
1,2015,3,8,3,1,WN,19393,N935WN,286,12892,32575,LAX,6,California,12191,31453,HOU,48,Texas,555,552.0,-3.0,0.0,0.0,-1.0,1115,1109.0,-6.0,0.0,0.0,-1.0,0.0,171.0,1.0,1390.0,6,None,None,None,None,None
2,2015,3,8,3,1,WN,19393,N935WN,60,12191,31453,HOU,48,Texas,11259,30194,DAL,48,Texas,2100,2216.0,76.0,76.0,1.0,5.0,2155,2311.0,76.0,76.0,1.0,5.0,0.0,39.0,1.0,239.0,1,72.0,0.0,0.0,0.0,4.0
3,2015,3,8,3,1,WN,19393,N935WN,950,14492,34492,RDU,37,North Carolina,12191,31453,HOU,48,Texas,1840,1951.0,71.0,71.0,1.0,4.0,2025,2133.0,68.0,68.0,1.0,4.0,0.0,147.0,1.0,1050.0,5,68.0,0.0,0.0,0.0,0.0
4,2015,3,8,3,1,WN,19393,N936WN,1009,11292,30325,DEN,8,Colorado,14679,33570,SAN,6,California,900,854.0,-6.0,0.0,0.0,-1.0,1015,1012.0,-3.0,0.0,0.0,-1.0,0.0,114.0,1.0,853.0,4,None,None,None,None,None

In [5]:
query = """

SELECT * FROM retard as a INNER JOIN avion as b on a.tailnum = b.tailnum limit 5;

            """

pd_sql.read_sql(query, connection)

,year,quarter,month,dayofmonth,dayofweek,uniquecarrier,airlineid,tailnum,flightnum,originairportid,origincitymarketid,origin,originstatefips,originstatename,destairportid,destcitymarketid,dest,deststatefips,deststatename,crsdeptime,deptime,depdelay,depdelayminutes,depdel15,departuredelaygroups,crsarrtime,arrtime,arrdelay,arrdelayminutes,arrdel15,arrivaldelaygroups,cancelled,airtime,flights,distance,distancegroup,carrierdelay,weatherdelay,nasdelay,securitydelay,lateaircraftdelay,tailnum,manufacturer,mfr_year,model,serial_number
0,2015,3,8,3,1,WN,19393,N935WN,253,13244,33244,MEM,47,Tennessee,13204,31454,MCO,12,Florida,1350,1353.0,3.0,3.0,0.0,0.0,1650,1700.0,10.0,10.0,0.0,0.0,0.0,109.0,1.0,684.0,3,None,None,None,None,None,N935WN,BOEING,2009,737-7H4,36641
1,2015,3,8,3,1,WN,19393,N935WN,286,12892,32575,LAX,6,California,12191,31453,HOU,48,Texas,555,552.0,-3.0,0.0,0.0,-1.0,1115,1109.0,-6.0,0.0,0.0,-1.0,0.0,171.0,1.0,1390.0,6,None,None,None,None,None,N935WN,BOEING,2009,737-7H4,36641
2,2015,3,8,3,1,WN,19393,N935WN,60,12191,31453,HOU,48,Texas,11259,30194,DAL,48,Texas,2100,2216.0,76.0,76.0,1.0,5.0,2155,2311.0,76.0,76.0,1.0,5.0,0.0,39.0,1.0,239.0,1,72.0,0.0,0.0,0.0,4.0,N935WN,BOEING,2009,737-7H4,36641
3,2015,3,8,3,1,WN,19393,N935WN,950,14492,34492,RDU,37,North Carolina,12191,31453,HOU,48,Texas,1840,1951.0,71.0,71.0,1.0,4.0,2025,2133.0,68.0,68.0,1.0,4.0,0.0,147.0,1.0,1050.0,5,68.0,0.0,0.0,0.0,0.0,N935WN,BOEING,2009,737-7H4,36641
4,2015,3,8,3,1,WN,19393,N936WN,1009,11292,30325,DEN,8,Colorado,14679,33570,SAN,6,California,900,854.0,-6.0,0.0,0.0,-1.0,1015,1012.0,-3.0,0.0,0.0,-1.0,0.0,114.0,1.0,853.0,4,None,None,None,None,None,N936WN,BOEING,2009,737-7H4,36643

In [10]:
query = """

SELECT * FROM retard as a INNER JOIN avion as b on a.tailnum = b.tailnum;

            """

df = pd_sql.read_sql(query, connection)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4958474 entries, 0 to 4958473
Data columns (total 46 columns):
year                    object
quarter                 object
month                   object
dayofmonth              object
dayofweek               object
uniquecarrier           object
airlineid               object
tailnum                 object
flightnum               object
originairportid         object
origincitymarketid      object
origin                  object
originstatefips         object
originstatename         object
destairportid           object
destcitymarketid        object
dest                    object
deststatefips           object
deststatename           object
crsdeptime              object
deptime                 object
depdelay                object
depdelayminutes         object
depdel15                object
departuredelaygroups    object
crsarrtime              object
arrtime                 object
arrdelay                object
arrdelayminutes         object
arrdel15                object
arrivaldelaygroups      object
cancelled               object
airtime                 object
flights                 object
distance                object
distancegroup           object
carrierdelay            object
weatherdelay            object
nasdelay                object
securitydelay           object
lateaircraftdelay       object
tailnum                 object
manufacturer            object
mfr_year                object
model                   object
serial_number           object
dtypes: object(46)
memory usage: 1.7+ GB

In [17]:
#import pickle    # the dataframe is too large for pickle
#with open('working_file.p', 'wb') as to_write:
#    pickle.dump(df, to_write)

In [12]:
df.to_csv('working_file.csv',index=False)

In [1]:
df.head(20)

In [16]:
list(df) # set the list to only keep field that can be made numeric

['year',
 'quarter',
 'month',
 'dayofmonth',
 'dayofweek',
 'uniquecarrier',
 'airlineid',
 'tailnum',
 'flightnum',
 'originairportid',
 'origincitymarketid',
 'origin',
 'originstatefips',
 'originstatename',
 'destairportid',
 'destcitymarketid',
 'dest',
 'deststatefips',
 'deststatename',
 'crsdeptime',
 'deptime',
 'depdelay',
 'depdelayminutes',
 'depdel15',
 'departuredelaygroups',
 'crsarrtime',
 'arrtime',
 'arrdelay',
 'arrdelayminutes',
 'arrdel15',
 'arrivaldelaygroups',
 'cancelled',
 'airtime',
 'flights',
 'distance',
 'distancegroup',
 'carrierdelay',
 'weatherdelay',
 'nasdelay',
 'securitydelay',
 'lateaircraftdelay',
 'tailnum',
 'manufacturer',
 'mfr_year',
 'model',
 'serial_number']

In [25]:
# we are only keeping columns that can become numeric
ndf = df.drop(
            ['year',
             #'quarter',
             #'month',
             #'dayofmonth',
             #'dayofweek',
             'uniquecarrier',
             #'airlineid',
             'tailnum',
             #'flightnum',
             #'originairportid',
             #'origincitymarketid',
             'origin',
             #'originstatefips',
             'originstatename',
             #'destairportid',
             #'destcitymarketid',
             'dest',
             #'deststatefips',
             'deststatename',
             #'crsdeptime',
             #'deptime',
             #'depdelay',
             #'depdelayminutes',
             #'depdel15',
             #'departuredelaygroups',
             #'crsarrtime',
             #'arrtime',
             #'arrdelay',
             #'arrdelayminutes',
             #'arrdel15',
             #'arrivaldelaygroups',
             #'cancelled',
             #'airtime',
             #'flights',
             #'distance',
             #'distancegroup',
             #'carrierdelay',
             #'weatherdelay',
             #'nasdelay',
             #'securitydelay',
             #'lateaircraftdelay',
             'tailnum',
             'manufacturer',
             #'mfr_year',
             'model']
             #'serial_number']
            ,axis = 1 )

In [26]:
ndf.head(5)

,quarter,month,dayofmonth,dayofweek,airlineid,flightnum,originairportid,origincitymarketid,originstatefips,destairportid,destcitymarketid,deststatefips,crsdeptime,deptime,depdelay,depdelayminutes,depdel15,departuredelaygroups,crsarrtime,arrtime,arrdelay,arrdelayminutes,arrdel15,arrivaldelaygroups,cancelled,airtime,flights,distance,distancegroup,carrierdelay,weatherdelay,nasdelay,securitydelay,lateaircraftdelay,mfr_year,serial_number
0,3,8,3,1,19393,253,13244,33244,47,13204,31454,12,1350,1353.0,3.0,3.0,0.0,0.0,1650,1700.0,10.0,10.0,0.0,0.0,0.0,109.0,1.0,684.0,3,None,None,None,None,None,2009,36641
1,3,8,3,1,19393,286,12892,32575,6,12191,31453,48,555,552.0,-3.0,0.0,0.0,-1.0,1115,1109.0,-6.0,0.0,0.0,-1.0,0.0,171.0,1.0,1390.0,6,None,None,None,None,None,2009,36641
2,3,8,3,1,19393,60,12191,31453,48,11259,30194,48,2100,2216.0,76.0,76.0,1.0,5.0,2155,2311.0,76.0,76.0,1.0,5.0,0.0,39.0,1.0,239.0,1,72.0,0.0,0.0,0.0,4.0,2009,36641
3,3,8,3,1,19393,950,14492,34492,37,12191,31453,48,1840,1951.0,71.0,71.0,1.0,4.0,2025,2133.0,68.0,68.0,1.0,4.0,0.0,147.0,1.0,1050.0,5,68.0,0.0,0.0,0.0,0.0,2009,36641
4,3,8,3,1,19393,1009,11292,30325,8,14679,33570,6,900,854.0,-6.0,0.0,0.0,-1.0,1015,1012.0,-3.0,0.0,0.0,-1.0,0.0,114.0,1.0,853.0,4,None,None,None,None,None,2009,36643

In [27]:
ndf.dtypes

quarter                 object
month                   object
dayofmonth              object
dayofweek               object
airlineid               object
flightnum               object
originairportid         object
origincitymarketid      object
originstatefips         object
destairportid           object
destcitymarketid        object
deststatefips           object
crsdeptime              object
deptime                 object
depdelay                object
depdelayminutes         object
depdel15                object
departuredelaygroups    object
crsarrtime              object
arrtime                 object
arrdelay                object
arrdelayminutes         object
arrdel15                object
arrivaldelaygroups      object
cancelled               object
airtime                 object
flights                 object
distance                object
distancegroup           object
carrierdelay            object
weatherdelay            object
nasdelay                object
securitydelay           object
lateaircraftdelay       object
mfr_year                object
serial_number           object
dtype: object

In [37]:
ndf['quarter'] = ndf['quarter'].astype(int)
ndf['month'] = ndf['month'].astype(int)
ndf['dayofmonth'] = ndf['dayofmonth'].astype(int)
ndf['dayofweek'] = ndf['dayofweek'].astype(int)
ndf['airlineid'] = ndf['airlineid'].astype(int)
ndf['flightnum'] = ndf['flightnum'].astype(int)
ndf['originairportid'] = ndf['originairportid'].astype(int)
ndf['origincitymarketid'] = ndf['origincitymarketid'].astype(int)
ndf['originstatefips'] = ndf['originstatefips'].astype(int) 
ndf['destairportid'] =  ndf['destairportid'].astype(int) 
ndf['destcitymarketid'] = ndf['destcitymarketid'].astype(int) 
ndf['deststatefips'] = ndf['deststatefips'].astype(int) 
ndf['crsdeptime'] = ndf['crsdeptime'].astype(int) 
ndf['deptime'] = pd.to_numeric(ndf['deptime'], errors='coerce').fillna(0,downcast='infer')
ndf['depdelay'] = pd.to_numeric(ndf['depdelay'], errors='coerce').fillna(0,downcast='infer')
ndf['depdelayminutes'] = pd.to_numeric(ndf['depdelayminutes'], errors='coerce').fillna(0)
ndf['depdel15'] = pd.to_numeric(ndf['depdel15'], errors='coerce').fillna(0)
ndf['departuredelaygroups'] = pd.to_numeric(ndf['departuredelaygroups'], errors='coerce').fillna(0)
ndf['crsarrtime'] = ndf['crsarrtime'].astype(int)
ndf['arrtime'] = pd.to_numeric(ndf['arrtime'], errors='coerce').fillna(0)
ndf['arrdelay'] = pd.to_numeric(ndf['arrdelay'], errors='coerce').fillna(0)
ndf['arrdelayminutes'] = pd.to_numeric(ndf['arrdelayminutes'], errors='coerce').fillna(0)
ndf['arrdel15'] = pd.to_numeric(ndf['arrdel15'], errors='coerce').fillna(0)
ndf['arrivaldelaygroups'] = pd.to_numeric(ndf['arrivaldelaygroups'], errors='coerce').fillna(0)
ndf['cancelled'] = pd.to_numeric(ndf['cancelled'], errors='coerce').fillna(0)
ndf['airtime'] = pd.to_numeric(ndf['airtime'], errors='coerce').fillna(0)
ndf['flights'] = pd.to_numeric(ndf['flights'], errors='coerce').fillna(0)
ndf['distance'] = pd.to_numeric(ndf['distance'], errors='coerce').fillna(0)
ndf['distancegroup'] = ndf['distancegroup'].astype(int)
ndf['carrierdelay'] = pd.to_numeric(ndf['carrierdelay'], errors='coerce').fillna(0,downcast='infer')
ndf['weatherdelay'] = pd.to_numeric(ndf['weatherdelay'], errors='coerce').fillna(0,downcast='infer')
ndf['nasdelay'] = pd.to_numeric(ndf['nasdelay'], errors='coerce').fillna(0,downcast='infer')
ndf['securitydelay'] = pd.to_numeric(ndf['securitydelay'], errors='coerce').fillna(0,downcast='infer')
ndf['lateaircraftdelay'] = pd.to_numeric(ndf['lateaircraftdelay'], errors='coerce').fillna(0,downcast='infer')
ndf['mfr_year'] = pd.to_numeric(ndf['mfr_year'], errors='coerce').fillna(0,downcast='infer')
ndf['serial_number'] = pd.to_numeric(ndf['serial_number'], errors='coerce').fillna(0,downcast='infer')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [38]:
#ndf.to_csv('numeric_file.csv',index=False) 
ndf.dtypes

quarter                   int64
month                     int64
dayofmonth                int64
dayofweek                 int64
airlineid                 int64
flightnum                 int64
originairportid           int64
origincitymarketid        int64
originstatefips           int64
destairportid             int64
destcitymarketid          int64
deststatefips             int64
crsdeptime                int64
deptime                   int64
depdelay                  int64
depdelayminutes         float64
depdel15                float64
departuredelaygroups    float64
crsarrtime                int64
arrtime                 float64
arrdelay                float64
arrdelayminutes         float64
arrdel15                float64
arrivaldelaygroups      float64
cancelled               float64
airtime                 float64
flights                 float64
distance                float64
distancegroup             int64
carrierdelay              int64
weatherdelay              int64
nasdelay                  int64
securitydelay             int64
lateaircraftdelay         int64
mfr_year                  int64
serial_number           float64
dtype: object

In [39]:
# Now we have a dataframe of numbers only that we can save for further study
ndf.to_csv('./data/numeric_file.csv',index=False)

In [40]:
import pickle    # the limit for pickle is around 1.7GB - THIS FILE IS 1.43GB
with open('./data/numeric_file.p', 'wb') as to_write:
    pickle.dump(ndf, to_write)